#!/bin/bash

drop_table() {

    while true; do
        read -p "Please enter the name of the table you want to delete: " file_name

        if [[ -z "$file_name" ]]; then
            echo "Table name cannot be empty."
            continue
        fi

        break
    done

    found=false


    for file in *.SQL; do
  
        [[ "$file" == .* ]] && continue

        if [ "$file_name.SQL" = "$file" ]; then
            [ -e "$file" ] || continue
            [ -f "$file" ] || continue
            rm "$file"
            echo "Table '${file%.SQL}' deleted successfully"
            found=true
            break
        fi
    done

    $found || echo "Table not found"
}

drop_table



