#!/bin/bash
list_tables() {

    found=false

    for file in *.SQL
    do
       
        [ -e "$file" ] || continue

       
        [ -f "$file" ] || continue

       
        [[ "$file" == .* ]] && continue

       
        echo "${file%.SQL}"

        found=true
    done

   
    $found || echo "No tables found"
}
list_tables
